type_bodies = {
    'Muffalo': 'QuadrupedAnimalWithHooves',
    'Gazelle': 'QuadrupedAnimalWithHooves',
    'Iguana': 'QuadrupedAnimalWithClawsTailAndJowl',
    'Rhinoceros': 'QuadrupedAnimalWithHoovesAndHorn',
    'Dromedary': 'QuadrupedAnimalWithHoovesAndHump',
    'Bear_Grizzly': 'QuadrupedAnimalWithPaws',
    'Bear_Polar': 'QuadrupedAnimalWithPaws',
    'Cougar': 'QuadrupedAnimalWithPawsAndTail',
    'Panther': 'QuadrupedAnimalWithPawsAndTail',
    'Lynx': 'QuadrupedAnimalWithPawsAndTail',
    'Cassowary': 'Bird',
    'Emu': 'Bird',
    'Ostrich': 'Bird',
    'Turkey': 'Bird',
    'Chicken': 'Bird',
    'Pig': 'QuadrupedAnimalWithHooves',
    'Cow': 'QuadrupedAnimalWithHooves',
    'Alpaca': 'QuadrupedAnimalWithHooves',
    'Elephant': 'QuadrupedAnimalWithHoovesTusksAndTrunk',
    'Megasloth': 'QuadrupedAnimalWithPawsAndTail',
    'Thrumbo': 'QuadrupedAnimalWithHoovesAndHorn',
    'Hare': 'QuadrupedAnimalWithPawsAndTail',
    'Snowhare': 'QuadrupedAnimalWithPawsAndTail',
    'Megascarab': 'BeetleLike',
    'Spelopede': 'BeetleLikeWithClaw',
    'Megaspider': 'BeetleLikeWithClaw',
    'YorkshireTerrier': 'QuadrupedAnimalWithPawsAndTail',
    'Husky': 'QuadrupedAnimalWithPawsAndTail',
    'LabradorRetriever': 'QuadrupedAnimalWithPawsAndTail',
    'Cat': 'QuadrupedAnimalWithPawsAndTail',
    'Squirrel': 'QuadrupedAnimalWithPawsAndTail',
    'Alphabeaver': 'QuadrupedAnimalWithPawsAndTail',
    'Capybara': 'QuadrupedAnimalWithPaws',
    'Chinchilla': 'QuadrupedAnimalWithPawsAndTail',
    'Boomrat': 'QuadrupedAnimalWithPaws',
    'Raccoon': 'QuadrupedAnimalWithPaws',
    'Rat': 'QuadrupedAnimalWithPaws',
    'Deer': 'QuadrupedAnimalWithHooves',
    'Ibex': 'QuadrupedAnimalWithHooves',
    'Elk': 'QuadrupedAnimalWithHooves',
    'Caribou': 'QuadrupedAnimalWithHooves',
    'WildBoar': 'QuadrupedAnimalWithHoovesAndTusks',
    'Tortoise': 'TurtleLike',
    'Cobra': 'Snake',
    'Monkey': 'Monkey',
    'Boomalope': 'QuadrupedAnimalWithHoovesAndHump',
    'Warg': 'QuadrupedAnimalWithPawsAndTail',
    'Wolf_Timber': 'QuadrupedAnimalWithPawsAndTail',
    'Wolf_Arctic': 'QuadrupedAnimalWithPawsAndTail',
    'Fox_Fennec': 'QuadrupedAnimalWithPawsAndTail',
    'Fox_Red': 'QuadrupedAnimalWithPawsAndTail',
    'Fox_Arctic': 'QuadrupedAnimalWithPawsAndTail',
    'Human': 'Human',
    'Mech_Centipede': 'MechanicalCentipede',
    'Mech_Lancer': 'Lancer',
    'Mech_Scyther': 'Scyther',
}
body_parts = {
    'Bird': [
        'Body',
        'Tail',
        'Spine',
        'Stomach',
        'Heart',
        'Lung',
        'Lung',
        'Kidney',
        'Kidney',
        'Liver',
        'Neck',
        'Head',
        'Skull',
        'Brain',
        'Eye',
        'Eye',
        'Beak',
        'Leg',
        'Foot',
        'Leg',
        'Foot',
    ],
    'BeetleLike': [
        'Shell',
        'Elytra',
        'Elytra',
        'Stomach',
        'InsectHeart',
        'Pronotum',
        'InsectHead',
        'Brain',
        'Eye',
        'Eye',
        'Antenna',
        'Antenna',
        'InsectNostril',
        'InsectMouth',
        'InsectLeg',
        'InsectLeg',
        'InsectLeg',
        'InsectLeg',
        'InsectLeg',
        'InsectLeg',
    ],
    'BeetleLikeWithClaw': [
        'Shell',
        'Elytra',
        'Elytra',
        'Stomach',
        'InsectHeart',
        'Pronotum',
        'InsectHead',
        'Brain',
        'Eye',
        'Eye',
        'Antenna',
        'Antenna',
        'InsectNostril',
        'InsectMouth',
        'HeadClaw',
        'InsectLeg',
        'InsectLeg',
        'InsectLeg',
        'InsectLeg',
        'InsectLeg',
        'InsectLeg',
    ],
    'QuadrupedAnimalWithPaws': [
        'Body',
        'Spine',
        'Stomach',
        'Heart',
        'Lung',
        'Lung',
        'Kidney',
        'Kidney',
        'Liver',
        'Neck',
        'Head',
        'Skull',
        'Brain',
        'Eye',
        'Eye',
        'Ear',
        'Ear',
        'Nose',
        'AnimalJaw',
        'Leg',
        'Paw',
        'Leg',
        'Paw',
        'Leg',
        'Paw',
        'Leg',
        'Paw',
    ],
    'QuadrupedAnimalWithPawsAndTail': [
        'Body',
        'Tail',
        'Spine',
        'Stomach',
        'Heart',
        'Lung',
        'Lung',
        'Kidney',
        'Kidney',
        'Liver',
        'Neck',
        'Head',
        'Skull',
        'Brain',
        'Eye',
        'Eye',
        'Ear',
        'Ear',
        'Nose',
        'AnimalJaw',
        'Leg',
        'Paw',
        'Leg',
        'Paw',
        'Leg',
        'Paw',
        'Leg',
        'Paw',
    ],
    'QuadrupedAnimalWithHooves': [
        'Body',
        'Spine',
        'Stomach',
        'Heart',
        'Lung',
        'Lung',
        'Kidney',
        'Kidney',
        'Liver',
        'Neck',
        'Head',
        'Skull',
        'Brain',
        'Eye',
        'Eye',
        'Ear',
        'Ear',
        'Nose',
        'AnimalJaw',
        'Leg',
        'Hoof',
        'Leg',
        'Hoof',
        'Leg',
        'Hoof',
        'Leg',
        'Hoof',
    ],
    'QuadrupedAnimalWithHoovesAndHump': [
        'Body',
        'Spine',
        'Stomach',
        'Heart',
        'Lung',
        'Lung',
        'Kidney',
        'Kidney',
        'Liver',
        'Hump',
        'Neck',
        'Head',
        'Skull',
        'Brain',
        'Eye',
        'Eye',
        'Ear',
        'Ear',
        'Nose',
        'AnimalJaw',
        'Leg',
        'Hoof',
        'Leg',
        'Hoof',
        'Leg',
        'Hoof',
        'Leg',
        'Hoof',
    ],
    'QuadrupedAnimalWithHoovesAndTusks': [
        'Body',
        'Spine',
        'Stomach',
        'Heart',
        'Lung',
        'Lung',
        'Kidney',
        'Kidney',
        'Liver',
        'Neck',
        'Head',
        'Skull',
        'Brain',
        'Eye',
        'Eye',
        'Ear',
        'Ear',
        'Nose',
        'AnimalJaw',
        'Tusk',
        'Tusk',
        'Leg',
        'Hoof',
        'Leg',
        'Hoof',
        'Leg',
        'Hoof',
        'Leg',
        'Hoof',
    ],
    'QuadrupedAnimalWithHoovesTusksAndTrunk': [
        'Body',
        'Spine',
        'Stomach',
        'Heart',
        'Lung',
        'Lung',
        'Kidney',
        'Kidney',
        'Liver',
        'Neck',
        'Head',
        'Skull',
        'Brain',
        'Eye',
        'Eye',
        'Ear',
        'Ear',
        'Trunk',
        'AnimalJaw',
        'Tusk',
        'Tusk',
        'Leg',
        'Hoof',
        'Leg',
        'Hoof',
        'Leg',
        'Hoof',
        'Leg',
        'Hoof',
    ],
    'QuadrupedAnimalWithHoovesAndHorn': [
        'Body',
        'Spine',
        'Stomach',
        'Heart',
        'Lung',
        'Lung',
        'Kidney',
        'Kidney',
        'Liver',
        'Neck',
        'Head',
        'Skull',
        'Brain',
        'Eye',
        'Eye',
        'Ear',
        'Ear',
        'Nose',
        'Horn',
        'AnimalJaw',
        'Leg',
        'Hoof',
        'Leg',
        'Hoof',
        'Leg',
        'Hoof',
        'Leg',
        'Hoof',
    ],
    'QuadrupedAnimalWithClawsTailAndJowl': [
        'Body',
        'Tail',
        'Spine',
        'Stomach',
        'Heart',
        'Lung',
        'Lung',
        'Kidney',
        'Kidney',
        'Liver',
        'Neck',
        'Head',
        'Skull',
        'Brain',
        'Eye',
        'Eye',
        'Ear',
        'Ear',
        'Nose',
        'AnimalJaw',
        'Jowl',
        'Leg',
        'FrontClaw',
        'FrontClaw',
        'FrontClaw',
        'FrontClaw',
        'FrontClaw',
        'Leg',
        'FrontClaw',
        'FrontClaw',
        'FrontClaw',
        'FrontClaw',
        'FrontClaw',
        'Leg',
        'RearClaw',
        'RearClaw',
        'RearClaw',
        'RearClaw',
        'RearClaw',
        'Leg',
        'RearClaw',
        'RearClaw',
        'RearClaw',
        'RearClaw',
        'RearClaw',
    ],
    'TurtleLike': [
        'TurtleShell',
        'Plastron',
        'Tail',
        'Spine',
        'Stomach',
        'Heart',
        'Lung',
        'Lung',
        'Kidney',
        'Kidney',
        'Liver',
        'Head',
        'Brain',
        'Eye',
        'Eye',
        'Nose',
        'TurtleBeak',
        'Leg',
        'Leg',
        'Leg',
        'Leg',
    ],
    'Monkey': [
        'Torso',
        'Tail',
        'Clavicle',
        'Clavicle',
        'Ribcage',
        'Sternum',
        'Pelvis',
        'Spine',
        'Stomach',
        'Heart',
        'Lung',
        'Lung',
        'Kidney',
        'Kidney',
        'Liver',
        'Neck',
        'Head',
        'Skull',
        'Brain',
        'Eye',
        'Eye',
        'Ear',
        'Ear',
        'Nose',
        'AnimalJaw',
        'Shoulder',
        'Arm',
        'Humerus',
        'Radius',
        'Hand',
        'Finger',
        'Finger',
        'Finger',
        'Finger',
        'Finger',
        'Shoulder',
        'Arm',
        'Humerus',
        'Radius',
        'Hand',
        'Finger',
        'Finger',
        'Finger',
        'Finger',
        'Finger',
        'Leg',
        'Femur',
        'Tibia',
        'Foot',
        'Toe',
        'Toe',
        'Toe',
        'Toe',
        'Toe',
        'Leg',
        'Femur',
        'Tibia',
        'Foot',
        'Toe',
        'Toe',
        'Toe',
        'Toe',
        'Toe',
    ],
    'Snake': [
        'SnakeBody',
        'Stomach',
        'Heart',
        'Lung',
        'Lung',
        'Kidney',
        'Kidney',
        'Liver',
        'SnakeHead',
        'Skull',
        'Brain',
        'Eye',
        'Eye',
        'Nose',
        'SnakeMouth',
    ],
    'Human': [
        'Torso',
        'Ribcage',
        'Sternum',
        'Pelvis',
        'Spine',
        'Stomach',
        'Heart',
        'Lung',
        'Lung',
        'Kidney',
        'Kidney',
        'Liver',
        'Neck',
        'Head',
        'Skull',
        'Brain',
        'Eye',
        'Eye',
        'Ear',
        'Ear',
        'Nose',
        'Jaw',
        'Shoulder',
        'Clavicle',
        'Arm',
        'Humerus',
        'Radius',
        'Hand',
        'Finger',
        'Finger',
        'Finger',
        'Finger',
        'Finger',
        'Shoulder',
        'Clavicle',
        'Arm',
        'Humerus',
        'Radius',
        'Hand',
        'Finger',
        'Finger',
        'Finger',
        'Finger',
        'Finger',
        'Waist',
        'Leg',
        'Femur',
        'Tibia',
        'Foot',
        'Toe',
        'Toe',
        'Toe',
        'Toe',
        'Toe',
        'Leg',
        'Femur',
        'Tibia',
        'Foot',
        'Toe',
        'Toe',
        'Toe',
        'Toe',
        'Toe',
    ],
    'MechanicalCentipede': [
        'MechanicalCentipedeBodyFirstRing',
        'MechanicalHead',
        'ArtificialBrain',
        'SightSensor',
        'SightSensor',
        'HearingSensor',
        'HearingSensor',
        'SmellSensor',
        'MechanicalCentipedeBodySecondRing',
        'MechanicalCentipedeBodyThirdRing',
        'MechanicalCentipedeBodyFourthRing',
        'MechanicalCentipedeBodyFifthRing',
        'MechanicalCentipedeBodySixthRing',
    ],
    'Lancer': [
        'MechanicalThorax',
        'MechanicalNeck',
        'MechanicalHead',
        'ArtificialBrain',
        'SightSensor',
        'SightSensor',
        'HearingSensor',
        'HearingSensor',
        'SmellSensor',
        'MechanicalShoulder',
        'MechanicalArm',
        'MechanicalHand',
        'MechanicalFinger',
        'MechanicalFinger',
        'MechanicalFinger',
        'MechanicalFinger',
        'MechanicalShoulder',
        'MechanicalArm',
        'MechanicalHand',
        'MechanicalFinger',
        'MechanicalFinger',
        'MechanicalFinger',
        'MechanicalFinger',
        'MechanicalLeg',
        'MechanicalFoot',
        'MechanicalLeg',
        'MechanicalFoot',
    ],
    'Scyther': [
        'MechanicalThorax',
        'MechanicalNeck',
        'MechanicalHead',
        'ArtificialBrain',
        'SightSensor',
        'SightSensor',
        'HearingSensor',
        'HearingSensor',
        'SmellSensor',
        'MechanicalShoulder',
        'MechanicalArm',
        'Blade',
        'MechanicalHand',
        'MechanicalFinger',
        'MechanicalFinger',
        'MechanicalFinger',
        'MechanicalFinger',
        'MechanicalShoulder',
        'MechanicalArm',
        'Blade',
        'MechanicalHand',
        'MechanicalFinger',
        'MechanicalFinger',
        'MechanicalFinger',
        'MechanicalFinger',
        'MechanicalLeg',
        'MechanicalFoot',
        'MechanicalLeg',
        'MechanicalFoot',
    ],
}
