version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7.15-jessie

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            pip install lxml pytest

      - run:
          name: run tests
          command: |
            py.test -vv

      - store_artifacts:
          path: test-reports
          destination: test-reports
          
