type_bodies = {
    'Muffalo': 'QuadrupedAnimalWithHooves',
    'Gazelle': 'QuadrupedAnimalWithHooves',
    'Iguana': 'QuadrupedAnimalWithClawsTailAndJowl',
    'Rhinoceros': 'QuadrupedAnimalWithHoovesAndHorn',
    'Dromedary': 'QuadrupedAnimalWithHoovesAndHump',
    'GrizzlyBear': 'QuadrupedAnimalWithPaws',
    'PolarBear': 'QuadrupedAnimalWithPaws',
    'Cougar': 'QuadrupedAnimalWithPawsAndTail',
    'Panther': 'QuadrupedAnimalWithPawsAndTail',
    'Lynx': 'QuadrupedAnimalWithPawsAndTail',
    'Cassowary': 'Bird',
    'Emu': 'Bird',
    'Ostrich': 'Bird',
    'Turkey': 'Bird',
    'Chicken': 'Bird',
    'Pig': 'QuadrupedAnimalWithHooves',
    'Cow': 'QuadrupedAnimalWithHooves',
    'Alpaca': 'QuadrupedAnimalWithHooves',
    'Elephant': 'QuadrupedAnimalWithHoovesTusksAndTrunk',
    'Megasloth': 'Human',
    'Thrumbo': 'QuadrupedAnimalWithHoovesAndHorn',
    'Hare': 'QuadrupedAnimalWithPawsAndTail',
    'Snowhare': 'QuadrupedAnimalWithPawsAndTail',
    'Megascarab': 'BeetleLike',
    'Spelopede': 'BeetleLikeWithClaw',
    'Megaspider': 'BeetleLikeWithClaw',
    'YorkshireTerrier': 'QuadrupedAnimalWithPawsAndTail',
    'Husky': 'QuadrupedAnimalWithPawsAndTail',
    'LabradorRetriever': 'QuadrupedAnimalWithPawsAndTail',
    'Cat': 'QuadrupedAnimalWithPawsAndTail',
    'Squirrel': 'QuadrupedAnimalWithPawsAndTail',
    'Alphabeaver': 'QuadrupedAnimalWithPawsAndTail',
    'Capybara': 'QuadrupedAnimalWithPaws',
    'Chinchilla': 'QuadrupedAnimalWithPawsAndTail',
    'Boomrat': 'QuadrupedAnimalWithPaws',
    'Raccoon': 'QuadrupedAnimalWithPaws',
    'Rat': 'QuadrupedAnimalWithPaws',
    'Deer': 'QuadrupedAnimalWithHooves',
    'Ibex': 'QuadrupedAnimalWithHooves',
    'Elk': 'QuadrupedAnimalWithHooves',
    'Caribou': 'QuadrupedAnimalWithHooves',
    'WildBoar': 'QuadrupedAnimalWithHoovesAndTusks',
    'Tortoise': 'TurtleLike',
    'Cobra': 'Snake',
    'Monkey': 'Monkey',
    'Boomalope': 'QuadrupedAnimalWithHoovesAndHump',
    'Warg': 'QuadrupedAnimalWithPawsAndTail',
    'WolfTimber': 'QuadrupedAnimalWithPawsAndTail',
    'WolfArctic': 'QuadrupedAnimalWithPawsAndTail',
    'FoxFennec': 'QuadrupedAnimalWithPawsAndTail',
    'FoxRed': 'QuadrupedAnimalWithPawsAndTail',
    'FoxArctic': 'QuadrupedAnimalWithPawsAndTail',
    'Human': 'Human',
    'Mechanoid_Centipede': 'MechanicalCentipede',
    'Mechanoid_Scyther': 'Scyther',
}
body_parts = {
    'Bird': [
        'Body',
        'Tail',
        'Spine',
        'Stomach',
        'Heart',
        'LeftLung',
        'RightLung',
        'LeftKidney',
        'RightKidney',
        'Liver',
        'Neck',
        'Head',
        'Skull',
        'Brain',
        'LeftEye',
        'RightEye',
        'Beak',
        'LeftLeg',
        'LeftFoot',
        'RightLeg',
        'RightFoot',
    ],
    'BeetleLike': [
        'Shell',
        'LeftElytra',
        'RightElytra',
        'Stomach',
        'InsectHeart',
        'Pronotum',
        'InsectHead',
        'Brain',
        'LeftEye',
        'RightEye',
        'LeftAntenna',
        'RightAntenna',
        'InsectNostril',
        'InsectMouth',
        'FrontLeftInsectLeg',
        'FrontRightInsectLeg',
        'MiddleLeftInsectLeg',
        'MiddleRightInsectLeg',
        'RearLeftInsectLeg',
        'RearRightInsectLeg',
    ],
    'BeetleLikeWithClaw': [
        'Shell',
        'LeftElytra',
        'RightElytra',
        'Stomach',
        'InsectHeart',
        'Pronotum',
        'InsectHead',
        'Brain',
        'LeftEye',
        'RightEye',
        'LeftAntenna',
        'RightAntenna',
        'InsectNostril',
        'InsectMouth',
        'HeadClaw',
        'FrontLeftInsectLeg',
        'FrontRightInsectLeg',
        'MiddleLeftInsectLeg',
        'MiddleRightInsectLeg',
        'RearLeftInsectLeg',
        'RearRightInsectLeg',
    ],
    'QuadrupedAnimalWithPaws': [
        'Body',
        'Spine',
        'Stomach',
        'Heart',
        'LeftLung',
        'RightLung',
        'LeftKidney',
        'RightKidney',
        'Liver',
        'Neck',
        'Head',
        'Skull',
        'Brain',
        'LeftEye',
        'RightEye',
        'LeftEar',
        'RightEar',
        'Nose',
        'AnimalJaw',
        'FrontLeftLeg',
        'FrontLeftPaw',
        'FrontRightLeg',
        'FrontRightPaw',
        'RearLeftLeg',
        'RearLeftPaw',
        'RearRightLeg',
        'RearRightPaw',
    ],
    'QuadrupedAnimalWithPawsAndTail': [
        'Body',
        'Tail',
        'Spine',
        'Stomach',
        'Heart',
        'LeftLung',
        'RightLung',
        'LeftKidney',
        'RightKidney',
        'Liver',
        'Neck',
        'Head',
        'Skull',
        'Brain',
        'LeftEye',
        'RightEye',
        'LeftEar',
        'RightEar',
        'Nose',
        'AnimalJaw',
        'FrontLeftLeg',
        'FrontLeftPaw',
        'FrontRightLeg',
        'FrontRightPaw',
        'RearLeftLeg',
        'RearLeftPaw',
        'RearRightLeg',
        'RearRightPaw',
    ],
    'QuadrupedAnimalWithHooves': [
        'Body',
        'Spine',
        'Stomach',
        'Heart',
        'LeftLung',
        'RightLung',
        'LeftKidney',
        'RightKidney',
        'Liver',
        'Neck',
        'Head',
        'Skull',
        'Brain',
        'LeftEye',
        'RightEye',
        'LeftEar',
        'RightEar',
        'Nose',
        'AnimalJaw',
        'FrontLeftLeg',
        'FrontLeftHoof',
        'FrontRightLeg',
        'FrontRightHoof',
        'RearLeftLeg',
        'RearLeftHoof',
        'RearRightLeg',
        'RearRightHoof',
    ],
    'QuadrupedAnimalWithHoovesAndHump': [
        'Body',
        'Spine',
        'Stomach',
        'Heart',
        'LeftLung',
        'RightLung',
        'LeftKidney',
        'RightKidney',
        'Liver',
        'Hump',
        'Neck',
        'Head',
        'Skull',
        'Brain',
        'LeftEye',
        'RightEye',
        'LeftEar',
        'RightEar',
        'Nose',
        'AnimalJaw',
        'FrontLeftLeg',
        'FrontLeftHoof',
        'FrontRightLeg',
        'FrontRightHoof',
        'RearLeftLeg',
        'RearLeftHoof',
        'RearRightLeg',
        'RearRightHoof',
    ],
    'QuadrupedAnimalWithHoovesAndTusks': [
        'Body',
        'Spine',
        'Stomach',
        'Heart',
        'LeftLung',
        'RightLung',
        'LeftKidney',
        'RightKidney',
        'Liver',
        'Neck',
        'Head',
        'Skull',
        'Brain',
        'LeftEye',
        'RightEye',
        'LeftEar',
        'RightEar',
        'Nose',
        'AnimalJaw',
        'LeftTusk',
        'RightTusk',
        'FrontLeftLeg',
        'FrontLeftHoof',
        'FrontRightLeg',
        'FrontRightHoof',
        'RearLeftLeg',
        'RearLeftHoof',
        'RearRightLeg',
        'RearRightHoof',
    ],
    'QuadrupedAnimalWithHoovesTusksAndTrunk': [
        'Body',
        'Spine',
        'Stomach',
        'Heart',
        'LeftLung',
        'RightLung',
        'LeftKidney',
        'RightKidney',
        'Liver',
        'Neck',
        'Head',
        'Skull',
        'Brain',
        'LeftEye',
        'RightEye',
        'LeftEar',
        'RightEar',
        'Trunk',
        'AnimalJaw',
        'LeftTusk',
        'RightTusk',
        'FrontLeftLeg',
        'FrontLeftHoof',
        'FrontRightLeg',
        'FrontRightHoof',
        'RearLeftLeg',
        'RearLeftHoof',
        'RearRightLeg',
        'RearRightHoof',
    ],
    'QuadrupedAnimalWithHoovesAndHorn': [
        'Body',
        'Spine',
        'Stomach',
        'Heart',
        'LeftLung',
        'RightLung',
        'LeftKidney',
        'RightKidney',
        'Liver',
        'Neck',
        'Head',
        'Skull',
        'Brain',
        'LeftEye',
        'RightEye',
        'LeftEar',
        'RightEar',
        'Nose',
        'Horn',
        'AnimalJaw',
        'FrontLeftLeg',
        'FrontLeftHoof',
        'FrontRightLeg',
        'FrontRightHoof',
        'RearLeftLeg',
        'RearLeftHoof',
        'RearRightLeg',
        'RearRightHoof',
    ],
    'QuadrupedAnimalWithClawsTailAndJowl': [
        'Body',
        'Tail',
        'Spine',
        'Stomach',
        'Heart',
        'LeftLung',
        'RightLung',
        'LeftKidney',
        'RightKidney',
        'Liver',
        'Neck',
        'Head',
        'Skull',
        'Brain',
        'LeftEye',
        'RightEye',
        'LeftEar',
        'RightEar',
        'Nose',
        'AnimalJaw',
        'Jowl',
        'FrontLeftLeg',
        'FrontLeftLegFirstClaw',
        'FrontLeftLegSecondClaw',
        'FrontLeftLegThirdClaw',
        'FrontLeftLegFourthClaw',
        'FrontLeftLegFifthClaw',
        'FrontRightLeg',
        'FrontRightLegFirstClaw',
        'FrontRightLegSecondClaw',
        'FrontRightLegThirdClaw',
        'FrontRightLegFourthClaw',
        'FrontRightLegFifthClaw',
        'RearLeftLeg',
        'RearLeftLegFirstClaw',
        'RearLeftLegSecondClaw',
        'RearLeftLegThirdClaw',
        'RearLeftLegFourthClaw',
        'RearLeftLegFifthClaw',
        'RearRightLeg',
        'RearRightLegFirstClaw',
        'RearRightLegSecondClaw',
        'RearRightLegThirdClaw',
        'RearRightLegFourthClaw',
        'RearRightLegFifthClaw',
    ],
    'TurtleLike': [
        'TurtleShell',
        'Plastron',
        'Tail',
        'Spine',
        'Stomach',
        'Heart',
        'LeftLung',
        'RightLung',
        'LeftKidney',
        'RightKidney',
        'Liver',
        'Head',
        'Brain',
        'LeftEye',
        'RightEye',
        'Nose',
        'TurtleBeak',
        'FrontLeftLeg',
        'FrontRightLeg',
        'RearLeftLeg',
        'RearRightLeg',
    ],
    'Monkey': [
        'Torso',
        'Tail',
        'LeftClavicle',
        'RightClavicle',
        'Sternum',
        'Rib',
        'Rib',
        'Rib',
        'Rib',
        'Rib',
        'Rib',
        'Rib',
        'Rib',
        'Rib',
        'Rib',
        'Rib',
        'Rib',
        'Pelvis',
        'Spine',
        'Stomach',
        'Heart',
        'LeftLung',
        'RightLung',
        'LeftKidney',
        'RightKidney',
        'Liver',
        'Neck',
        'Head',
        'Skull',
        'Brain',
        'LeftEye',
        'RightEye',
        'LeftEar',
        'RightEar',
        'Nose',
        'AnimalJaw',
        'LeftShoulder',
        'LeftArm',
        'LeftHumerus',
        'LeftRadius',
        'LeftHand',
        'LeftHandPinky',
        'LeftHandRingFinger',
        'LeftHandMiddleFinger',
        'LeftHandIndexFinger',
        'LeftHandThumb',
        'RightShoulder',
        'RightArm',
        'RightHumerus',
        'RightRadius',
        'RightHand',
        'RightHandPinky',
        'RightHandRingFinger',
        'RightHandMiddleFinger',
        'RightHandIndexFinger',
        'RightHandThumb',
        'LeftLeg',
        'LeftFemur',
        'LeftTibia',
        'LeftFoot',
        'LeftFootLittleToe',
        'LeftFootFourthToe',
        'LeftFootMiddleToe',
        'LeftFootSecondToe',
        'LeftFootBigToe',
        'RightLeg',
        'RightFemur',
        'RightTibia',
        'RightFoot',
        'RightFootLittleToe',
        'RightFootFourthToe',
        'RightFootMiddleToe',
        'RightFootSecondToe',
        'RightFootBigToe',
    ],
    'Snake': [
        'SnakeBody',
        'Stomach',
        'Heart',
        'LeftLung',
        'RightLung',
        'LeftKidney',
        'RightKidney',
        'Liver',
        'SnakeHead',
        'Skull',
        'Brain',
        'LeftEye',
        'RightEye',
        'Nose',
        'SnakeMouth',
    ],
    'Human': [
        'Torso',
        'Sternum',
        'Rib',
        'Rib',
        'Rib',
        'Rib',
        'Rib',
        'Rib',
        'Rib',
        'Rib',
        'Rib',
        'Rib',
        'Rib',
        'Rib',
        'Pelvis',
        'Spine',
        'Stomach',
        'Heart',
        'LeftLung',
        'RightLung',
        'LeftKidney',
        'RightKidney',
        'Liver',
        'Neck',
        'Head',
        'Skull',
        'Brain',
        'LeftEye',
        'RightEye',
        'LeftEar',
        'RightEar',
        'Nose',
        'Jaw',
        'LeftShoulder',
        'LeftClavicle',
        'LeftArm',
        'LeftHumerus',
        'LeftRadius',
        'LeftHand',
        'LeftHandPinky',
        'LeftHandRingFinger',
        'LeftHandMiddleFinger',
        'LeftHandIndexFinger',
        'LeftHandThumb',
        'RightShoulder',
        'RightClavicle',
        'RightArm',
        'RightHumerus',
        'RightRadius',
        'RightHand',
        'RightHandPinky',
        'RightHandRingFinger',
        'RightHandMiddleFinger',
        'RightHandIndexFinger',
        'RightHandThumb',
        'Waist',
        'LeftLeg',
        'LeftFemur',
        'LeftTibia',
        'LeftFoot',
        'LeftFootLittleToe',
        'LeftFootFourthToe',
        'LeftFootMiddleToe',
        'LeftFootSecondToe',
        'LeftFootBigToe',
        'RightLeg',
        'RightFemur',
        'RightTibia',
        'RightFoot',
        'RightFootLittleToe',
        'RightFootFourthToe',
        'RightFootMiddleToe',
        'RightFootSecondToe',
        'RightFootBigToe',
    ],
    'MechanicalCentipede': [
        'MechanicalCentipedeBodyFirstRing',
        'MechanicalHead',
        'ArtificialBrain',
        'LeftSightSensor',
        'RightSightSensor',
        'LeftHearingSensor',
        'RightHearingSensor',
        'SmellSensor',
        'MechanicalCentipedeBodySecondRing',
        'MechanicalCentipedeBodyThirdRing',
        'MechanicalCentipedeBodyFourthRing',
        'MechanicalCentipedeBodyFifthRing',
        'MechanicalCentipedeBodySixthRing',
    ],
    'Scyther': [
        'MechanicalThorax',
        'MechanicalNeck',
        'MechanicalHead',
        'ArtificialBrain',
        'LeftSightSensor',
        'RightSightSensor',
        'LeftHearingSensor',
        'RightHearingSensor',
        'SmellSensor',
        'LeftMechanicalShoulder',
        'LeftMechanicalArm',
        'LeftBlade',
        'LeftMechanicalHand',
        'LeftHandMechanicalPinky',
        'LeftHandMechanicalMiddleFinger',
        'LeftHandMechanicalIndexFinger',
        'LeftHandMechanicalThumb',
        'RightMechanicalShoulder',
        'RightMechanicalArm',
        'RightBlade',
        'RightMechanicalHand',
        'RightHandMechanicalPinky',
        'RightHandMechanicalMiddleFinger',
        'RightHandMechanicalIndexFinger',
        'RightHandMechanicalThumb',
        'LeftMechanicalLeg',
        'LeftMechanicalFoot',
        'RightMechanicalLeg',
        'RightMechanicalFoot',
    ],
}
